== Get all job advertisements belonging to the owner

=== Request

`GET {api-url}/jobAdvertisements/v1?page=0&size25`

[cols="10,10,10,70"]
|===
| Parameter | Constraints | Default | Description

| page | Optional | 0 | The page that should be returned
| size | Optional | 25 | The maximum number of elements on the page
|===

=== Response

[source,json]
----
{
   "content":[
      {
      "id": "4feae516-d62c-11e9-ab5e-005056ac3479",
      "status": "INSPECTING",
      "sourceSystem": "API",
      "externalReference": "1234",
      "stellennummerEgov": "300002290",
      "stellennummerAvam": null,
      "fingerprint": null,
      "reportingObligation": true,
      "reportingObligationEndDate": null,
      "reportToAvam": false,
      "jobCenterCode": "BEAF0",
      "approvalDate": null,
      "rejectionDate": null,
      "rejectionCode": null,
      "rejectionReason": null,
      "cancellationDate": null,
      "cancellationCode": null,
      "jobContent": {
        "externalUrl": "https://jobs.admin.ch/offene-stellen/Bauarbeiter-1234",
        "numberOfJobs": "1",
        "jobDescriptions": [
          {
            "languageIsoCode": "de",
            "title": "Bauarbeiter",
            "description":
             "# Anforderungen
             - Zwingende Baustellenkenntnisse im Hoch- und Tiefbau
             - Kenntnisse in den Schalungssystemen Doka, Peri, Meva und Noe
             - Sicherheitsschulung von Vorteil
             - Handwerkliches Geschick

             # Aufgaben
             - Betonieren
             - Ein- und Ausschalen
             - Aufräumen der Baustelle
             - Allgemeine Mithilfe auf Hoch- und Tiefbau Baustellen"
          }
        ],
        "company": {
          "name": "Muster AG",
          "street": "Münsterstrasse",
          "houseNumber": "9",
          "postalCode": "3007",
          "city": "Bern",
          "countryIsoCode": "CH",
          "postOfficeBoxNumber": null,
          "postOfficeBoxPostalCode": null,
          "postOfficeBoxCity": null,
          "phone": "+41 32 123 45 67",
          "email": "info@musterag.ch",
          "website": "https://www.musterag.ch",
          "surrogate": true
        },
        "employment": {
          "startDate": "2020-01-20",
          "endDate": null,
          "shortEmployment": false,
          "immediately": false,
          "permanent": true,
          "workloadPercentageMin": "100",
          "workloadPercentageMax": "100",
          "workForms": [
            "NIGHT_WORK"
          ]
        },
        "location": {
          "remarks": null,
          "city": "Bern",
          "postalCode": "3003",
          "communalCode": "351",
          "regionCode": "BE01",
          "cantonCode": "BE",
          "countryIsoCode": "CH",
          "coordinates": null
        },
        "occupations": [
          {
            "avamOccupationCode": "52502",
            "workExperience": "LESS_THAN_1_YEAR",
            "educationCode": "132"
          }
        ],
        "languageSkills": [
          {
            "languageIsoCode": "de",
            "spokenLevel": "PROFICIENT",
            "writtenLevel": "INTERMEDIATE"
          }
        ],
        "applyChannel": {
          "mailAddress": null,
          "emailAddress": "bewerbungen@musterag.ch",
          "phoneNumber": "+41 31 123 45 67",
          "formUrl": null,
          "additionalInfo": null
        },
        "publicContact": {
          "salutation": "MR",
          "firstName": "Max",
          "lastName": "Muster",
          "phone": "+41 31 123 45 67",
          "email": "max.muster@musterag.ch"
        }
      },
      "publication": {
        "startDate": "2020-01-01",
        "endDate": "2020-02-01",
        "euresDisplay": true,
        "euresAnonymous": false,
        "publicDisplay": true,
        "restrictedDisplay": true,
        "companyAnonymous": false
      }
    }
   ],
   "currentElements":0,
   "currentPage":0,
   "first":true,
   "last":true,
   "totalElements":0,
   "totalPages":0
}
----

[cols="10,90"]
|===
| Name | Description

| content | The list of job advertisements
| currentElements | The number of job advertisements on this page
| currentPage | The current page number
| first | `true` if there are no previous pages
| last | `true` if there are no following pages
| totalElements | The total number of job advertisements on all pages
| totalPages | The total number of pages
|===

=== Response status

[cols="10,20,70"]
|===
| Code | Status | Description

| 200 | Ok | The page with job ads has been returned
| 401 | Unauthorized | User is not logged in
| 403 | Forbidden | User has not the required permission to perform this action
|===

