== Create a new job advertisement

=== Fields

==== JobAdvertisement
[cols="30,10,30,20,50"]
|===
| Path | Type | Description | Constraints | Notes

| externalUrl | String(1024) | Link to the original website of the job ad | Optional | For jobs that fall under the reporting obligation, the ad must not be published elsewhere.
| externalReference | String(255) | Your internal reference to this job ad | Optional |
| reportToAvam | Boolean | Should the ad be transmitted to the PES (RAV)? | Required (`true` or `false`) | Usually false. Use this option if you want a PES agent to know about your vacancy
| numberOfJobs | String(3) | The number of identical positions | Optional | Use this option only if you have a number of identical vacancies. The number will be transmitted to the PES agent. 
| contact | <<Contact>> | Contact person about the job ad | Required | Administrative contact; not for publication, will be treated confidentially
| jobDescriptions | Array<<<JobDescription>>> | Language specific title and description | Required 1..4 | The text of the job advertisement; may be multilingual
| company | <<Company>> | The company that handles the recruitment | Required | May be a private placement agency or hiring of services agency
| employer | <<Employer>> | The actual employer that offers the job | Required, if _company.surrogate_ is `true` | Not for publication, will be treated confidentially
| employment | <<Employment>> | Certain employment conditions | Required |
| location | <<Location>> | The work location | Required |
| occupation | <<Occupation>> | Occupation, education and work experience | Required |
| languageSkills | Array<<<LanguageSkill>>> | It is possible to define up to 5 language skills required by the job. | 0..5 objects |
| publicContact | <<PublicContact>> | Contact person for the job seekers questions | Optional | Will be published in Job-Room
| applyChannel | <<ApplyChannel>> | Different application channels | Required | Provide at least one application channel
| publication | <<Publication>> | The publication platforms | Required | You can control how your ad is published
|===

==== Contact
Provide an administrative contact (e. g. an HR employee).

Important: this contact is used for email notifications concerning the reporting obligation.
The contact details are not for publication and will be treated confidentially.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| languageIsoCode | String(5) | The language of correspondence | Required (ISO 639-1), must be one of de, fr, it,en
| salutation | String(3) |  | Required (`MR` or `MS`)
| firstName | String(50) |  | Required
| lastName | String(50) |  | Required
| phone | String(20) |  | Required (Format: +41123456789)
| email | String(50) | Only one valid address allowed | Required
|===

==== JobDescription
The text of the job advertisement; may be multilingual
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| languageIsoCode | String(5) | The language of the title and description | Required (ISO 639-1) but only de, fr, it or en
| title | String(255) | Job title or occupation | Required
| description | String(10'000) | Job description cannot contain html formatting. Use markdown formating instead | Required (Max 10'000 characters)
|===

==== Company
The company that handles the recruitment. This information is published.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| name | String(255) | The name of the company | Required
| street | String(50) | | Provide a street or post office box address
| houseNumber | String(10) | | Provide a street or post office box address
| postOfficeBoxNumber | String(10) | | Provide a street or post office box address
| postOfficeBoxPostalCode | String(10) | | Optional
| postOfficeBoxCity | String(100) | | Optional
| postalCode | String(10) | | Required. Must be a valid swiss postal code if the company is located in Switzerland
| city | String(100) | | Required
| countryIsoCode | String(2) | | Required (ISO 3166-1 alpha-2)
| website | String(255) | | Optional (Format: http://www.example.org)
| phone | String(20) | | Optional (Format: +41123456789)
| email | String(50) | Only one address allowed | Optional
| surrogate | Boolean | Does the company act as a surrogate for the actual employer? | Required (`true` or `false`)
|===

==== Employer
If the recruitment is handled by a private placement agency or hiring of services agency, the _company.surrogate_ flag
MUST be set to `true` and the actual employer information MUST be provided. This information is required for
administrative purposes and will be treated strictly confidentially by SECO and the Public Employment Service.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| name | String(255) | The name of the original company | Required
| city | String(100) | | Required
| postalCode | String(10) | | Required. Must be a valid swiss postal code if the company is located in Switzerland
| countryIsoCode | String(2) | | Required (ISO 3166-1 alpha-2)
|===

==== Employment
Employment metadata
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| startDate | String(10) | When does the job start | Optional (Format: 2018-01-20)
| endDate | String(10) | When does the contract end | Optional (Format: 2018-01-20)
| shortEmployment | Boolean | Is the employment duration 14 days or less | Required (`true` or `false`)
| immediately | Boolean | Does the job start immediately | Required (`true` or `false`) `true` only if no startDate is set
| permanent | Boolean | Is the contract permanent | Required (`true` or `false`) `true` only if no endDate is set
| workloadPercentageMin | String(3) | | Required (10..100 less or equal workloadPercentageMax)
| workloadPercentageMax | String(3) | | Required (10..100 greater or equal workloadPercentageMin)
| workForms | Array<String> | Special work requirements | Optional (`SUNDAY_AND_HOLIDAYS`, `SHIFT_WORK`, `NIGHT_WORK`, `HOME_WORK`)
|===

==== Location
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| postalCode | String(10) | | Required. Must be a valid swiss postal code if the company is located in Switzerland
| city | String(50) | The (main) place of work | Required
| countryIsoCode | String(2) | | Required (ISO 3166-1 alpha-2)
| remarks | String(255) | More information about job location can be added as free text.
|===

==== Occupation
The ad must be coded to an occupation according ot the AVAM occupation list; this determines the reporting obligation.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| avamOccupationCode | String(16) | <<AVAM occupation code>>  | Required
| workExperience | String(64) | | Optional (`LESS_THAN_1_YEAR`, `MORE_THAN_1_YEAR` or `MORE_THAN_3_YEARS`)
| educationCode | String(8) | <<AVAM education code>> | Optional
|===

==== LanguageSkill
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| languageIsoCode | String(5) | | Required (ISO 639-1)
| spokenLevel | String(64) | | Required (`NONE`, `BASIC`, `INTERMEDIATE` or `PROFICIENT`) (see https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages#Common_reference_levels[Common reference levels])
| writtenLevel | String(64) | | Required (`NONE`, `BASIC`, `INTERMEDIATE` or `PROFICIENT`) (see https://en.wikipedia.org/wiki/Common_European_Framework_of_Reference_for_Languages#Common_reference_levels[Common reference levels])
|===

==== ApplyChannel
Provide at least one channel for applications.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| formUrl | String(255) | An online form where an applicant can apply | Optional (Format: http://www.example.org)
| emailAddress | String(50) | An email address where an applicant can send their application | Optional
| phoneNumber | String(20) | A phone number where an applicant can call | Optional (Format: +41123456789)
| mailAddress | String(255) | A post address where an applicant can send their application | Optional
| additionalInfo | String(255) | Currently not used, will be ignored | Optional (do not use)
|===

==== PublicContact
Provide a public contact if you want to give applicants the opportunity to ask questions about the job.
The contact details will be published.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| salutation | String(3) |  | Required (`MR` or `MS`)
| firstName | String(50) |  | Required
| lastName | String(50) |  | Required
| phone | String(20) |  | Optional (Format: +41123456789) (phone or email must be set)
| email | String(50) |  | Optional (phone or email must be set)
|===

==== Publication
If the ad falls under the reporting obligation, the ad will be restricted for five business days.
After that period, the ad will be published
in the Job-Room public area if the publicDisplay flag is set, otherwise not.
[cols="30,10,30,30"]
|===
| Path | Type | Description | Constraints

| startDate | String(10) | When does the advertisement publication start | Required (Format: 2018-01-20)
| endDate | String(10) | When does the advertisement publication end (max 60 days) | Optional (Format: 2018-01-20)
| euresDisplay | Boolean | Should the job ad be displayed in Eures | Required (`true` or `false`)
| publicDisplay | Boolean | Should the job ad be displayed in Job-Room public area | Required (`true` or `false`)
|===

=== Request
`POST {api-url}/jobAdvertisements/v1`

[source,json]
----
{
   "externalUrl":"https://jobs.admin.ch/offene-stellen/Bauarbeiter-1234",
   "externalReference":"1234",
   "reportToAvam":false,
   "numberOfJobs":1,
   "contact":{
      "languageIsoCode":"de",
      "salutation":"MR",
      "firstName":"Max",
      "lastName":"Mustermann",
      "phone":"+41311234567",
      "email":"max.mustermann@example.com"
   },
   "jobDescriptions":[
      {
         "languageIsoCode":"de",
         "title":"Bauarbeiter",
         "description":
         "# Anforderungen
         - Zwingende Baustellenkenntnisse im Hoch- und Tiefbau
         - Kenntnisse in den Schalungssystemen Doka, Peri, Meva und Noe
         - Sicherheitsschulung von Vorteil
         - Handwerkliches Geschick

         # Aufgaben
         - Betonieren
         - Ein- und Ausschalen
         - Aufr채umen der Baustelle
         - Allgemeine Mithilfe auf Hoch- und Tiefbau Baustellen"
      }
   ],
   "company":{
      "name":"Muster AG",
      "street":"M체nsterstrasse",
      "houseNumber":"9",
      "postOfficeBoxNumber":null,
      "postOfficeBoxPostalCode":null,
      "postOfficeBoxCity":null,
      "postalCode":"3007",
      "city":"Bern",
      "countryIsoCode":"CH",
      "website":"https://www.musterag.ch",
      "phone":"+41321234567",
      "email":"info@musterag.ch",
      "surrogate":true
   },
   "employer":{
      "name":"Example company",
      "postalCode":"1200",
      "city":"Geneva",
      "countryIsoCode":"CH"
   },
   "employment":{
      "startDate":"2020-01-20",
      "endDate":null,
      "shortEmployment":false,
      "immediately":false,
      "permanent":true,
      "workloadPercentageMax":100,
      "workloadPercentageMin":100,
      "workForms":[
         "NIGHT_WORK"
      ]
   },
   "location":{
      "remarks":null,
      "postalCode":"3003",
      "city":"Bern",
      "countryIsoCode":"CH"
   },
   "occupation":{
      "avamOccupationCode":"52502",
      "workExperience":"LESS_THAN_1_YEAR",
      "educationCode":"132"
   },
   "languageSkills":[
      {
         "languageIsoCode":"de",
         "spokenLevel":"PROFICIENT",
         "writtenLevel":"INTERMEDIATE"
      }
   ],
   "applyChannel":{
      "mailAddress":null,
      "emailAddress":"bewerbungen@musterag.ch",
      "phoneNumber":"+41311234567",
      "formUrl":null,
      "additionalInfo":null
   },
   "publicContact":{
      "salutation":"MR",
      "firstName":"Max",
      "lastName":"Muster",
      "phone":"+41311234567",
      "email":"max.muster@musterag.ch"
   },
   "publication":{
      "startDate":"2020-01-01",
      "endDate":"2020-02-01",
      "euresDisplay":true,
      "publicDisplay":true
   }
}
----

=== Response
The response provides the _id_ needed to later retrieve the object via Get.
The flag _reportingObligation_ indicates whether the ad falls under the reporting obligation,
based on the occupation code provided.

[source,json]
----
{
  "id": "4feae516-d62c-11e9-ab5e-005056ac3479",
  "status": "INSPECTING",
  "sourceSystem": "API",
  "externalReference": "1234",
  "stellennummerEgov": "300002290",
  "stellennummerAvam": null,
  "fingerprint": null,
  "reportingObligation": true,
  "reportingObligationEndDate": null,
  "reportToAvam": false,
  "jobCenterCode": "BEAF0",
  "approvalDate": null,
  "rejectionDate": null,
  "rejectionCode": null,
  "rejectionReason": null,
  "cancellationDate": null,
  "cancellationCode": null,
  "jobContent": {
    "externalUrl": "https://jobs.admin.ch/offene-stellen/Bauarbeiter-1234",
    "numberOfJobs": "1",
    "jobDescriptions": [
      {
        "languageIsoCode": "de",
        "title": "Bauarbeiter",
        "description":
         "# Anforderungen
         - Zwingende Baustellenkenntnisse im Hoch- und Tiefbau
         - Kenntnisse in den Schalungssystemen Doka, Peri, Meva und Noe
         - Sicherheitsschulung von Vorteil
         - Handwerkliches Geschick

         # Aufgaben
         - Betonieren
         - Ein- und Ausschalen
         - Aufr채umen der Baustelle
         - Allgemeine Mithilfe auf Hoch- und Tiefbau Baustellen"
      }
    ],
    "company": {
      "name": "Muster AG",
      "street": "M체nsterstrasse",
      "houseNumber": "9",
      "postalCode": "3007",
      "city": "Bern",
      "countryIsoCode": "CH",
      "postOfficeBoxNumber": null,
      "postOfficeBoxPostalCode": null,
      "postOfficeBoxCity": null,
      "phone": "+41 32 123 45 67",
      "email": "info@musterag.ch",
      "website": "https://www.musterag.ch",
      "surrogate": true
    },
    "employment": {
      "startDate": "2020-01-20",
      "endDate": null,
      "shortEmployment": false,
      "immediately": false,
      "permanent": true,
      "workloadPercentageMin": "100",
      "workloadPercentageMax": "100",
      "workForms": [
        "NIGHT_WORK"
      ]
    },
    "location": {
      "remarks": null,
      "city": "Bern",
      "postalCode": "3003",
      "communalCode": "351",
      "regionCode": "BE01",
      "cantonCode": "BE",
      "countryIsoCode": "CH",
      "coordinates": null
    },
    "occupations": [
      {
        "avamOccupationCode": "52502",
        "workExperience": "LESS_THAN_1_YEAR",
        "educationCode": "132"
      }
    ],
    "languageSkills": [
      {
        "languageIsoCode": "de",
        "spokenLevel": "PROFICIENT",
        "writtenLevel": "INTERMEDIATE"
      }
    ],
    "applyChannel": {
      "mailAddress": null,
      "emailAddress": "bewerbungen@musterag.ch",
      "phoneNumber": "+41 31 123 45 67",
      "formUrl": null,
      "additionalInfo": null
    },
    "publicContact": {
      "salutation": "MR",
      "firstName": "Max",
      "lastName": "Muster",
      "phone": "+41 31 123 45 67",
      "email": "max.muster@musterag.ch"
    }
  },
  "publication": {
    "startDate": "2020-01-01",
    "endDate": "2020-02-01",
    "euresDisplay": true,
    "euresAnonymous": false,
    "publicDisplay": true,
    "restrictedDisplay": true,
    "companyAnonymous": false
  }
}
----

=== Access token
An access token is returned in the response headers.
The token can be used to check the state of jobs under the reporting obligation. The link is built according to the following
pattern:

`\https://www.job-room.ch/manage-job-ads/{id of job-ad}?token={token}`
[cols="10,20,70"]
|===
| Name | Type | Description
| token | String | The access token
|===

=== Response status
[cols="10,20,70"]
|===
| Code | Status | Description

| 201 | Created | The job ad has been successfully created
| 400 | Bad Request | The request was malformed or invalid
| 401 | Unauthorized | User is not logged in
| 403 | Forbidden | User has not the required permission to perform this action
|===

