spring:
    application:
        name: app-x28-job-ad-export

##############################
#  DATASOURCE CONFIG
##############################

    jpa:
        generate-ddl: false
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.jdbc.lob.non_contextual_creation: true # prevent error message: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.

    liquibase:
        enabled: false

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./build/h2db/db/batch;DB_CLOSE_DELAY=-1
        username: replace-with-username
        password: replace-with-password

    datasource:
        jobadservice:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:h2:file:./build/h2db/db/jobadservice;DB_CLOSE_DELAY=-1
            username: replace-with-username
            password: replace-with-password


##############################
#  X28 SFTP
##############################
jobroom:
    x28:
        sftp:
            localDirectory: /tmp/batch/job-ad-x28-export
            remoteDirectory: jobroom
            xmlFileName: avamJobs_test_current.xml
            host: admin.x28.ch
            username: replace-with-username
            password: replace-with-password
