##############################
#  PROJECT - INFO
##############################
info:
    project:
        version: #project.version#


##############################
#  JACKSON - ATTENTION: spring jackson proerties only apply when the spring-web library is present on the classpath !!
##############################


##############################
#  MESSAGEBROKER - KAFKA
##############################
spring:
    cloud:
        stream:
            bindings:
                output:
                    destination: jobad.action
                    group: x28-importer-task



##############################
#  X28 SFTP
##############################
jobroom:
    x28:
        sftp:
            localDirectory: /tmp/batch/job-ad-x28-import
            remoteDirectory: jobroom
            fileNamePattern: x28Jobs_seco_current.zip
            host: admin.x28.ch
            username: replace-with-username
            password: replace-with-password

##############################
#  LOGGING
##############################
logging:
    level:
        org.apache.kafka.clients: warn
