version: '2'
services:
#    spring-cloud-skipper:
#        build: spring-cloud-skipper
#        image: spring-cloud-skipper
#        environment:
#            SPRING_DATASOURCE_URL: jdbc:postgresql://spring-cloud-dataflow-postgres:5432/spring-cloud-dataflow
#            SPRING_DATASOURCE_USERNAME: spring-cloud-dataflow
#            SPRING_DATASOURCE_PASSWORD: s3cr3t
#            SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
#            MAVEN_LOCAL_REPOSITORY: /repo
#            MAVEN_REMOTE_REPOSITORIES_REPO1_URL: https://repo.spring.io/libs-release
#            MAVEN_REMOTE_REPOSITORIES_REPO2_URL: https://alvch.jfrog.io/alvch/global
#        volumes:
#            - ${HOME}/.m2/:/repo
#        ports:
#            - 7577:7577

    spring-cloud-dataflow:
        build: spring-cloud-dataflow
        image: spring-cloud-dataflow
        environment:
#            SPRING_CLOUD_DATAFLOW_FEATURES_SKIPPER_ENABLED: 'true'
            SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI: http://spring-cloud-skipper:7577/api
            SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
            SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: zookeeper:2181
            SPRING_CLOUD_DATAFLOW_APPLICATION_PROPERTIES_STREAM_SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
            SPRING_CLOUD_DATAFLOW_APPLICATION_PROPERTIES_STREAM_SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: zookeeper:2181
            SPRING_DATASOURCE_URL: jdbc:postgresql://spring-cloud-dataflow-postgres:5432/spring-cloud-dataflow
            SPRING_DATASOURCE_USERNAME: spring-cloud-dataflow
            SPRING_DATASOURCE_PASSWORD: s3cr3t
            SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
            MAVEN_LOCAL_REPOSITORY: /repo
            MAVEN_REMOTE_REPOSITORIES_SPRING_RELEASE: https://repo.spring.io/libs-release
            MAVEN_REMOTE_REPOSITORIES_ALVCH: https://alvch.jfrog.io/alvch/global
            LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_DEPLOYER: TRACE
        volumes:
            - ${HOME}/.m2/repository:/repo
        ports:
            - 9393:9393
            - 7000-7010:7000-7010

    spring-cloud-dataflow-postgres:
        image: postgres:latest
        environment:
            TZ: Europe/Zurich
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: spring-cloud-dataflow
            POSTGRES_PASSWORD: s3cr3t
        ports:
            - 5432:5432
        command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60
