spring:
  cloud:
    stream:
      bindings:
        input:
          destination: jobroom.event
          group: jobroom
        output:
          destination: jobroom.event
          group: jobroom
