spring:
    application:
        name: app-ws-avam-source

    jackson:
        generator:
            write_numbers_as_strings: true
        serialization:
            write_dates_as_timestamps: false

##############################
#  PROJECT - INFO
##############################
info:
    project:
        version: #project.version#
